[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "astrospec"
version = "0.1.0"
description = "A unified library of spectral models for astronomy."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
authors = [{ name = "Md. Khairul Islam" }]
dependencies = [
    "torch",
]

[project.optional-dependencies]
pretrained = ["huggingface_hub"]
aion = ["polymathic-aion"]
astroclip = ["lightning", "torchvision", "astropy", "jaxtyping"]
mamba = ["mamba-ssm"]
neuralop = ["neuraloperator"]

[project.urls]
Homepage = "https://github.com/khairulislam/AstroSpec"

[tool.setuptools.packages.find]
include = ["astrospec*"]
